### ISSUE TITLE
Wrong resolution parsing

### ISSUE THREAD

**Issue by ApolloBian** [dylanaraps/neofetch#1067]
## Description
I'm running neofetch on MacBook and it doesn't display screen resolution right

#### Neofetch version
Neofetch 5.0.1

## Screenshot
 - Neofetch output:
   <img width="389" alt="screen shot 2018-08-04 at 11 39 03 am" src="https://user-images.githubusercontent.com/13659369/43672163-18789266-97db-11e8-8364-cfeae8dd3569.png">
 - `system_profiler SPDisplaysDataType` output:
     <img width="642" alt="screen shot 2018-08-04 at 11 40 52 am" src="https://user-images.githubusercontent.com/13659369/43672182-4e7e8398-97db-11e8-95f0-3b06c274c364.png">

**Comment by ApolloBian** [comment]
It's the `get_resolution` func that needs to be fixed

**Comment by konimex** [comment]
I'm not sure what went wrong here.

Both show 3840 x 2160.

**Comment by ApolloBian** [comment]
@konimex the refresh rate is wrong, it shows `@4kHz`

**Comment by konimex** [comment]
Can you provide a full log?

Also, can you provide a *text* output (not image screenshot) of `system_profiler SPDisplaysDataType`)? The awk is a bit.. broken here. I guess.

**Comment by iandrewt** [comment]
Ah, looks like the output of `system_profiler SPDisplaysDataType` changed in Mojave. Like, breakingly different it seems. We'll need to add a check for Mojave to fix this one I think

**Comment by ApolloBian** [comment]
@konimex Here is the full output of `system_profiler SPDisplaysDataType`:
```
Graphics/Displays:

    Intel Iris Pro:

      Chipset Model: Intel Iris Pro
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x0d26
      Revision ID: 0x0008
      Metal: Supported, feature set macOS GPUFamily1 v4
      Displays:
        DELL U2718Q:
          Resolution: 3840 x 2160 (2160p 4K UHD - Ultra High Definition)
          UI Looks like: 1920 x 1080 @ 60 Hz
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Display Serial Number: 5DWRH7AU05LL
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
          Connection Type: DisplayPort
        DELL U2718Q:
          Resolution: 2160 x 3840
          UI Looks like: 1080 x 1920 @ 60 Hz
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Display Serial Number: 5DWRH7AQ12UL
          Mirror: Off
          Online: Yes
          Rotation: 90
          Automatically Adjust Brightness: No
          Connection Type: DisplayPort
```

Hope it helps!

**Comment by strafe** [comment]
@iandrewt I'm seeing the wrong resolution on High Sierra.
![image](https://user-images.githubusercontent.com/15663890/44289975-7b16e380-a26e-11e8-9bdf-f36e4569f029.png)
![image](https://user-images.githubusercontent.com/15663890/44289996-9386fe00-a26e-11e8-8d16-71f901ac12a5.png)

**Comment by dylanaraps** [comment]
ping @iandrewt

**Comment by Omega1902** [comment]
@iandrewt I have the same issue as @strafe with the wrong resolution 
My MacBook Pro 15" has a real resolution of 2880x1800
![bildschirmfoto 2018-10-17 um 09 04 06 1](https://user-images.githubusercontent.com/27062486/47068355-5c8c8480-d1ec-11e8-8916-e0d39b35648a.png)

**Comment by strafe** [comment]
Seems to be a problem with `screenresolution` rather than neofetch.
![image](https://user-images.githubusercontent.com/15663890/47112714-0f8dca00-d24f-11e8-9673-89677547d7c7.png)
![image](https://user-images.githubusercontent.com/15663890/47112741-1e747c80-d24f-11e8-9e5e-0a036770cdb3.png)

**Comment by iandrewt** [comment]
@Omega1902 are you running at 1440x900@2x?

Also, I'm pretty sure the 13" MacBook Pro defaults to 1440x900@2x now instead of 1280x800@2x like on pre-2016 models. The 15" is similar, defaulting to 1680x1050@2x instead of 1440x900@2x.

@dylanaraps are we intending to show the "UI Looks Like" or "Resolution"?

**Comment by dylanaraps** [comment]
Resolution (Full pixel w/h)

**Comment by iandrewt** [comment]
We'll have to remove `screenresolution` support if we want full pixel w/h, it outputs the "UI Looks Like" resolution. I'll try find a faster alternative to system_profiler too.

**Comment by Omega1902** [comment]
@iandrewt yes I did, without realizing... I changed to scaled resolution and now 1440x900@2x is displayed in neofetch.
Thanks! And thanks for the great work you do with the whole program ;)

**Comment by kode54** [comment]
Hey, look, I fixed it. Should I send a PR?

https://github.com/kode54/neofetch/commit/54376dbe8edd57422721ebb05821c9cf7c686142

<img width="592" alt="image" src="https://user-images.githubusercontent.com/796316/66630734-b59db700-ebb9-11e9-8ff8-fed8ee7b47f2.png">

**Comment by dylanaraps** [comment]
Sure, send a PR my way!

**Comment by strafe** [comment]
@dylanaraps since the maintainer of `screenresolution` is incredibly inactive and hasn't responded to certain PRs for 4+ years. We could always switch back to the upstream version if he ever decides to merge some of the outstanding PRs.

Could we consider:
- Forking `screenresolution` (with https://github.com/jhford/screenresolution/pull/33).
- Making a new tap/formula to serve it.
- Updating the `neofetch` Homebrew formula to use the forked version.

**Comment by AgentRin** [comment]
So I installed NeoFetch about 2 months ago. Since then I upgraded my Radeon Sapphire GPU to a Radeon RX 580. NeoFetch still shows the old GPU, but when I directly run `system_profiler SPDisplaysDataType` it shows the correct card.

![Screen Shot 2021-01-01 at 3 09 20 PM](https://user-images.githubusercontent.com/32678161/103447716-c1a0e900-4c43-11eb-8170-938c612812b7.png)

![Screen Shot 2021-01-01 at 3 09 49 PM](https://user-images.githubusercontent.com/32678161/103447718-c6659d00-4c43-11eb-9663-03788656a1e9.png)

Is there a cache to flush?

**Comment by vscsilva** [comment]
Neofetch still shows the wrong resolution.
Output o screenresolution:
![image](https://user-images.githubusercontent.com/64592232/126131480-69effbcb-584f-42ce-be8b-c689377031d9.png)

**Comment by PatrickBK** [comment]
> Seems to be a problem with `screenresolution` rather than neofetch. ![image](https://user-images.githubusercontent.com/15663890/47112714-0f8dca00-d24f-11e8-9673-89677547d7c7.png) ![image](https://user-images.githubusercontent.com/15663890/47112741-1e747c80-d24f-11e8-9e5e-0a036770cdb3.png)
> 
> After running `brew uninstall --ignore-dependencies screenresolution` the fallback to `system_profiler`'s output is accurate, although as mentioned in the changelog where `screenresolution` was introduced, there is a noticeable pause before the resolution is printed.

Yes, removing screenresolution works and in my experience neofetch doesn't slow down when doing so. Thanks :-)

![Schermafbeelding 2021-12-13 om 15 05 34](https://user-images.githubusercontent.com/526917/145826937-0fc8ba32-9b1a-418a-b24a-b0fef1097722.jpg)

**Comment by strafe** [comment]
> Yes, removing screenresolution works and in my experience neofetch doesn't slow down when doing so. Thanks :-)

You can compare the speeds for yourself with the `time` command, on my machine both are _"fast"_ but system_profiler is an order of magnitude slower than screensolution on average.

**Comment by kode54** [comment]
Unfortunately, screenresolution doesn't know how to retrieve the physical versus scaled down resolutions of a display. This is needed to retrieve the 1x versus 2x sizes of a display which is using scaling. Scaling is an arbitrary integer scale, but Apple mostly only supports 2x on desktop machines.

**Comment by strafe** [comment]
There is an open PR on screenresolution to add a new argument that returns the native resolution.

**Comment by cikupin** [comment]
on brew, I think we need to remove `screenresolution` from brew formula dependencies, to force it using `system_profiler SPDisplaysDataType`

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/neofetch.rb#L14

I've just submit an issue to homebrew. Hope that it can be fixed. https://github.com/Homebrew/homebrew-core/issues/94002

**Comment by strafe** [comment]
That's not going to be accepted because screenresolution is still used in neofetch, you'd need to make a PR removing it first. I think a better solution is to switch to the working fork on a private tap though.
