### ISSUE TITLE
[Feature Request]: Correct Shell, DE and WM on Windows

### ISSUE THREAD

**Issue by rashil2000** [dylanaraps/neofetch#1571]
## Description

Refer to this image: 

![94721313-55c49100-0373-11eb-8095-f4ff1844ed90](https://user-images.githubusercontent.com/46838874/94910730-bca49000-04c2-11eb-9ffa-80d82a1c97ae.png)

1. I think in most use cases the default shell being used on Windows is either PowerShell or CMD. Neofetch still returns bash. That's understandable because underneath it's using Cygwin/MINGW/Git Bash. But there should be an option to display PowerShell or CMD, or if none of these are detected, default to bash. If the OS is detected as Windows, the [COMSPEC](https://en.wikipedia.org/wiki/COMSPEC) (command interpreter specification) environment variable, which is available in Git Bash (since the environment is inherited) should be used. COMSPEC is always available in any Windows system, and usually points to `cmd.exe` but users change it to `powershell.exe` or `pwsh.exe` as well. This is the equivalent of `$SHELL` unix variable. This can be used in the `get_shell()` function. 

2. The DE on Windows 10 is Fluent, and not Aero. Refer to [this](https://en.wikipedia.org/wiki/Desktop_environment#Examples_of_desktop_environments) Wikipedia article. TL,DR; Luna was the DE on Windows XP, Aero on Windows Vista and 7, Metro on Windows 8 and 8.1, and Fluent on Windows 10. The fix (my estimate) for this should be fairly simple, just adding some 'case' statements in the `get_de()` function. 

3. Windows uses `DWM.exe` as the WM, as mentioned [here](https://en.wikipedia.org/wiki/Desktop_Window_Manager). `Explorer.exe` is responsible for the desktop, the file manager, the taskbar, and most visible components of the Windows shell. Both these are commonly confused with each other, refer to [this](https://stackoverflow.com/a/5220133) StackOverflow answer for more details. 

4. The GPU output is being weird here, but PR #1540 already fixes that. 

I might send a PR solving the above (except 4.) if I'm able to wrap my head around this stuff. 

#### Neofetch version

7.1.0

**Comment by dylanaraps** [comment]
Shell is not a bug as output is determined by the environment variable `$SHELL` and nothing else. I'm not sure about whether or not I want to add support for `COMSPEC`. I will revisit this later.

**Comment by rashil2000** [comment]
@dylanaraps Yes, I didn't say the Shell thing was a bug. I know it comes from the $SHELL variable. 

I would like to know what's exactly the issue with COMSPEC, if there's one.  

Also, would you mind keeping this issue open till this is resolved?

**Comment by dylanaraps** [comment]
If I decide that we want to support `COMSPEC`, I'll reopen this issue.

**Comment by rashil2000** [comment]
@dylanaraps I feel like it's my duty to point out that the changes you made in 4b5f4e3 regarding DE still don't work. You need a wildcard _both_ before and after `"Windows 10"` and `"Windows 8"`.  Please refer to my PR that was closed for the same.

**Comment by zikalify** [comment]
@rashil2000 do you know what code changes need making exactly? Perhaps you could make the changes so that @dylanaraps can accept them because this issue is still there.

**Comment by rashil2000** [comment]
@zikalify Which issue exactly?

**Comment by zikalify** [comment]
@rashil2000 The DE is still reporting as Aero on Windows 10 (and I assume 8 but can't test that). And the WM is still coming up as Explorer. Do you know how to fix those please?

**Comment by rashil2000** [comment]
@zikalify Did you try running the latest master?

**Comment by zikalify** [comment]
> @zikalify Did you try running the latest master?

Can I install it through Scoop? How do I update it?
Thanks
